"""initial schema

Revision ID: a62131789911
Revises:
Create Date: 2026-09-05 14:45:43.963392
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "a62131789911"
down_revision: str | None = None
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # pg_trgm backs ix_institutions_name_trgm (fuzzy name matching, ER blocking).
    # Must be created before the index, so it lives here, not in a manual step.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "denylist_learned",
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column(
            "added_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("added_by", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("url"),
    )
    op.create_table(
        "eval_gold",
        sa.Column("institution_key", sa.Text(), nullable=False),
        sa.Column("field", sa.Text(), nullable=False),
        sa.Column(
            "expected_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("verified_by", sa.Text(), nullable=False),
        sa.Column("verified_at", sa.Date(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("institution_key", "field"),
    )
    op.create_table(
        "groups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("canonical_name", sa.Text(), nullable=False),
        sa.Column("group_type", sa.Text(), nullable=False),
        sa.Column("legal_entity_name", sa.Text(), nullable=True),
        sa.Column("legal_entity_norm", sa.Text(), nullable=True),
        sa.Column("website", sa.Text(), nullable=True),
        sa.Column("hq_city", sa.Text(), nullable=True),
        sa.Column("hq_state", sa.Text(), nullable=True),
        sa.Column("campus_count", sa.Integer(), nullable=True),
        sa.Column("qualifying_campus_count", sa.Integer(), nullable=True),
        sa.Column("states_present", sa.ARRAY(sa.Text()), nullable=True),
        sa.Column("evidence", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "state", sa.Text(), server_default=sa.text("'pending'"), nullable=False
        ),
        sa.Column(
            "attempts", sa.SmallInteger(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "max_attempts",
            sa.SmallInteger(),
            server_default=sa.text("3"),
            nullable=False,
        ),
        sa.Column(
            "not_before",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("locked_by", sa.Text(), nullable=True),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("dedupe_key", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dedupe_key"),
    )
    op.create_index(
        "ix_jobs_not_before_pending",
        "jobs",
        ["not_before"],
        unique=False,
        postgresql_where=sa.text("state = 'pending'"),
    )
    op.create_table(
        "merge_decisions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("entity_key_a", sa.Text(), nullable=False),
        sa.Column("entity_key_b", sa.Text(), nullable=False),
        sa.Column("decision", sa.Text(), nullable=False),
        sa.Column("decided_by", sa.Text(), nullable=False),
        sa.Column(
            "decided_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("entity_key_a", "entity_key_b", name="uq_merge_pair"),
    )
    op.create_table(
        "overrides",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("entity_type", sa.Text(), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("field", sa.Text(), nullable=False),
        sa.Column(
            "value_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("author", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_overrides_live",
        "overrides",
        ["entity_type", "entity_id", "field"],
        unique=True,
        postgresql_where=sa.text("expires_at IS NULL"),
    )
    op.create_table(
        "people",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.Text(), nullable=False),
        sa.Column("normalized_name", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_people_normalized_name", "people", ["normalized_name"], unique=False
    )
    op.create_table(
        "pipeline_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("stage", sa.Text(), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rows_in", sa.Integer(), nullable=True),
        sa.Column("rows_out", sa.Integer(), nullable=True),
        sa.Column("ok", sa.Boolean(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("notes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "raw_documents",
        sa.Column("content_hash", sa.Text(), nullable=False),
        sa.Column("storage_path", sa.Text(), nullable=False),
        sa.Column("media_type", sa.Text(), nullable=False),
        sa.Column("bytes", sa.Integer(), nullable=False),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("content_hash"),
    )
    op.create_table(
        "review_queue",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("score", sa.Numeric(), nullable=True),
        sa.Column("state", sa.Text(), server_default=sa.text("'open'"), nullable=False),
        sa.Column("decided_by", sa.Text(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_review_queue_kind_score",
        "review_queue",
        ["kind", sa.literal_column("score DESC")],
        unique=False,
        postgresql_where=sa.text("state = 'open'"),
    )
    op.create_table(
        "source_registry",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("authority_tier", sa.SmallInteger(), nullable=False),
        sa.Column("robots_ok", sa.Boolean(), nullable=True),
        sa.Column("tos_note", sa.Text(), nullable=True),
        sa.Column("refresh_days", sa.Integer(), nullable=False),
        sa.Column(
            "rate_limit_rps",
            sa.Numeric(),
            server_default=sa.text("1.0"),
            nullable=False,
        ),
        sa.Column(
            "enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "fetches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column(
            "requested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("content_type", sa.Text(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("content_hash", sa.Text(), nullable=True),
        sa.Column("bytes", sa.Integer(), nullable=True),
        sa.Column("elapsed_ms", sa.Integer(), nullable=True),
        sa.Column("robots_allowed", sa.Boolean(), nullable=False),
        sa.Column("denylist_hit", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source_registry.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_fetches_content_hash", "fetches", ["content_hash"], unique=False
    )
    op.create_index(
        "ix_fetches_source_requested",
        "fetches",
        ["source_id", sa.literal_column("requested_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_fetches_url_requested",
        "fetches",
        ["url", sa.literal_column("requested_at DESC")],
        unique=False,
    )
    op.create_table(
        "institutions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("udise_code", sa.Text(), nullable=True),
        sa.Column("cbse_affiliation_no", sa.Text(), nullable=True),
        sa.Column("cisce_code", sa.Text(), nullable=True),
        sa.Column("ib_school_code", sa.Text(), nullable=True),
        sa.Column("cambridge_centre_no", sa.Text(), nullable=True),
        sa.Column("canonical_name", sa.Text(), nullable=False),
        sa.Column("institution_type", sa.Text(), nullable=False),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("pincode", sa.Text(), nullable=True),
        sa.Column("city", sa.Text(), nullable=True),
        sa.Column("district", sa.Text(), nullable=True),
        sa.Column("state", sa.Text(), nullable=True),
        sa.Column("metro_area", sa.Text(), nullable=True),
        sa.Column("lat", sa.Float(), nullable=True),
        sa.Column("lon", sa.Float(), nullable=True),
        sa.Column("geo_precision", sa.Text(), nullable=True),
        sa.Column("grade_low", sa.SmallInteger(), nullable=True),
        sa.Column("grade_high", sa.SmallInteger(), nullable=True),
        sa.Column("has_class_12", sa.Boolean(), nullable=True),
        sa.Column("streams", sa.ARRAY(sa.Text()), nullable=True),
        sa.Column("medium", sa.ARRAY(sa.Text()), nullable=True),
        sa.Column("gender", sa.Text(), nullable=True),
        sa.Column("residential", sa.Text(), nullable=True),
        sa.Column("fee_annual_inr_min", sa.Integer(), nullable=True),
        sa.Column("fee_annual_inr_max", sa.Integer(), nullable=True),
        sa.Column(
            "fee_annual_inr_mid",
            sa.Integer(),
            sa.Computed(
                "COALESCE((fee_annual_inr_min + fee_annual_inr_max) / 2, fee_annual_inr_min, fee_annual_inr_max)",
                persisted=True,
            ),
            nullable=True,
        ),
        sa.Column("fee_year", sa.SmallInteger(), nullable=True),
        sa.Column("total_enrollment", sa.Integer(), nullable=True),
        sa.Column("enrollment_year", sa.SmallInteger(), nullable=True),
        sa.Column("class_12_total", sa.Integer(), nullable=True),
        sa.Column("pcm_12_count", sa.Integer(), nullable=True),
        sa.Column("pcm_12_count_year", sa.SmallInteger(), nullable=True),
        sa.Column(
            "pcm_12_is_estimated",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("website", sa.Text(), nullable=True),
        sa.Column("email", sa.Text(), nullable=True),
        sa.Column("phone", sa.Text(), nullable=True),
        sa.Column("group_id", sa.Integer(), nullable=True),
        sa.Column("legal_entity_name", sa.Text(), nullable=True),
        sa.Column("legal_entity_norm", sa.Text(), nullable=True),
        sa.Column("management_type", sa.Text(), nullable=True),
        sa.Column(
            "status", sa.Text(), server_default=sa.text("'active'"), nullable=False
        ),
        sa.Column("year_founded", sa.SmallInteger(), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("search_tsv", postgresql.TSVECTOR(), nullable=True),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cambridge_centre_no"),
        sa.UniqueConstraint("cbse_affiliation_no"),
        sa.UniqueConstraint("cisce_code"),
        sa.UniqueConstraint("ib_school_code"),
        sa.UniqueConstraint("udise_code"),
    )
    op.create_index(
        "ix_institutions_class_12",
        "institutions",
        [sa.literal_column("class_12_total DESC NULLS LAST"), "id"],
        unique=False,
    )
    op.create_index(
        "ix_institutions_enrollment",
        "institutions",
        [sa.literal_column("total_enrollment DESC NULLS LAST"), "id"],
        unique=False,
    )
    op.create_index(
        "ix_institutions_fee_mid",
        "institutions",
        [sa.literal_column("fee_annual_inr_mid DESC NULLS LAST"), "id"],
        unique=False,
    )
    op.create_index(
        "ix_institutions_fee_min",
        "institutions",
        [sa.literal_column("fee_annual_inr_min DESC NULLS LAST"), "id"],
        unique=False,
    )
    op.create_index(
        "ix_institutions_group",
        "institutions",
        ["group_id"],
        unique=False,
        postgresql_where=sa.text("group_id IS NOT NULL"),
    )
    op.create_index(
        "ix_institutions_has_class_12",
        "institutions",
        ["has_class_12"],
        unique=False,
        postgresql_where=sa.text("has_class_12 = true"),
    )
    op.create_index(
        "ix_institutions_legal_entity_norm",
        "institutions",
        ["legal_entity_norm"],
        unique=False,
        postgresql_where=sa.text("legal_entity_norm IS NOT NULL"),
    )
    op.create_index(
        "ix_institutions_metro",
        "institutions",
        ["metro_area"],
        unique=False,
        postgresql_where=sa.text("metro_area IS NOT NULL"),
    )
    op.create_index(
        "ix_institutions_name_trgm",
        "institutions",
        ["canonical_name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"canonical_name": "gin_trgm_ops"},
    )
    op.create_index(
        "ix_institutions_pcm_12",
        "institutions",
        [sa.literal_column("pcm_12_count DESC NULLS LAST"), "id"],
        unique=False,
    )
    op.create_index(
        "ix_institutions_pincode", "institutions", ["pincode"], unique=False
    )
    op.create_index(
        "ix_institutions_search_tsv",
        "institutions",
        ["search_tsv"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "ix_institutions_state_city", "institutions", ["state", "city"], unique=False
    )
    op.create_table(
        "registry_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Text(), nullable=False),
        sa.Column(
            "taken_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["content_hash"],
            ["raw_documents.content_hash"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source_registry.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "institution_boards",
        sa.Column("institution_id", sa.Integer(), nullable=False),
        sa.Column("board", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=True),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["institution_id"], ["institutions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("institution_id", "board"),
    )
    op.create_table(
        "observations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("entity_type", sa.Text(), nullable=False),
        sa.Column("entity_key", sa.Text(), nullable=False),
        sa.Column("institution_id", sa.Integer(), nullable=True),
        sa.Column("group_id", sa.Integer(), nullable=True),
        sa.Column("field", sa.Text(), nullable=False),
        sa.Column("value_text", sa.Text(), nullable=True),
        sa.Column("value_num", sa.Numeric(), nullable=True),
        sa.Column("value_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("unit", sa.Text(), nullable=True),
        sa.Column("source_id", sa.Text(), nullable=False),
        sa.Column("fetch_id", sa.Integer(), nullable=True),
        sa.Column("content_hash", sa.Text(), nullable=True),
        sa.Column("evidence_span", sa.Text(), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "extracted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("extractor", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Numeric(), nullable=False),
        sa.Column("superseded_by", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1", name="ck_observations_confidence"
        ),
        sa.ForeignKeyConstraint(
            ["content_hash"],
            ["raw_documents.content_hash"],
        ),
        sa.ForeignKeyConstraint(
            ["fetch_id"],
            ["fetches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["institution_id"],
            ["institutions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source_registry.id"],
        ),
        sa.ForeignKeyConstraint(
            ["superseded_by"],
            ["observations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_observations_entity_field",
        "observations",
        ["entity_key", "field"],
        unique=False,
    )
    op.create_index(
        "ix_observations_hash_extractor",
        "observations",
        ["content_hash", "extractor"],
        unique=False,
    )
    op.create_index(
        "ix_observations_institution_field",
        "observations",
        ["institution_id", "field"],
        unique=False,
        postgresql_where=sa.text("institution_id IS NOT NULL"),
    )
    op.create_index(
        "uq_observations_live",
        "observations",
        ["content_hash", "extractor", "entity_key", "field"],
        unique=True,
        postgresql_where=sa.text("superseded_by IS NULL"),
    )
    op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("person_id", sa.Integer(), nullable=False),
        sa.Column("institution_id", sa.Integer(), nullable=True),
        sa.Column("group_id", sa.Integer(), nullable=True),
        sa.Column("title_raw", sa.Text(), nullable=False),
        sa.Column("title_normalized", sa.Text(), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=True),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "institution_id IS NOT NULL OR group_id IS NOT NULL",
            name="ck_roles_has_subject",
        ),
        sa.ForeignKeyConstraint(["group_id"], ["groups.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["institution_id"], ["institutions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["people.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_roles_institution_title",
        "roles",
        ["institution_id", "title_normalized"],
        unique=False,
    )
    op.create_table(
        "scores",
        sa.Column("institution_id", sa.Integer(), nullable=False),
        sa.Column("model_version", sa.Text(), nullable=False),
        sa.Column(
            "campaign", sa.Text(), server_default=sa.text("'default'"), nullable=False
        ),
        sa.Column(
            "computed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("fit", sa.Numeric(), nullable=False),
        sa.Column("confidence", sa.Numeric(), nullable=False),
        sa.Column(
            "components", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "flags", sa.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 100", name="ck_scores_confidence"
        ),
        sa.CheckConstraint("fit >= 0 AND fit <= 100", name="ck_scores_fit"),
        sa.ForeignKeyConstraint(
            ["institution_id"], ["institutions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint(
            "institution_id", "model_version", "campaign", "computed_at"
        ),
    )
    op.create_index(
        "ix_scores_model_campaign_fit",
        "scores",
        ["model_version", "campaign", sa.literal_column("fit DESC")],
        unique=False,
    )
    op.create_table(
        "signals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("institution_id", sa.Integer(), nullable=True),
        sa.Column("group_id", sa.Integer(), nullable=True),
        sa.Column("signal_type", sa.Text(), nullable=False),
        sa.Column(
            "detected_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("event_date", sa.Date(), nullable=True),
        sa.Column(
            "before_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("after_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("source_id", sa.Text(), nullable=False),
        sa.Column("evidence_fetch_id", sa.Integer(), nullable=True),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["evidence_fetch_id"],
            ["fetches.id"],
        ),
        sa.ForeignKeyConstraint(["group_id"], ["groups.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["institution_id"], ["institutions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source_registry.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_signals_institution_type_date",
        "signals",
        ["institution_id", "signal_type", "event_date"],
        unique=True,
        postgresql_where=sa.text("institution_id IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_signals_institution_type_date",
        table_name="signals",
        postgresql_where=sa.text("institution_id IS NOT NULL"),
    )
    op.drop_table("signals")
    op.drop_index("ix_scores_model_campaign_fit", table_name="scores")
    op.drop_table("scores")
    op.drop_index("ix_roles_institution_title", table_name="roles")
    op.drop_table("roles")
    op.drop_index(
        "uq_observations_live",
        table_name="observations",
        postgresql_where=sa.text("superseded_by IS NULL"),
    )
    op.drop_index(
        "ix_observations_institution_field",
        table_name="observations",
        postgresql_where=sa.text("institution_id IS NOT NULL"),
    )
    op.drop_index("ix_observations_hash_extractor", table_name="observations")
    op.drop_index("ix_observations_entity_field", table_name="observations")
    op.drop_table("observations")
    op.drop_table("institution_boards")
    op.drop_table("registry_snapshots")
    op.drop_index("ix_institutions_state_city", table_name="institutions")
    op.drop_index(
        "ix_institutions_search_tsv", table_name="institutions", postgresql_using="gin"
    )
    op.drop_index("ix_institutions_pincode", table_name="institutions")
    op.drop_index("ix_institutions_pcm_12", table_name="institutions")
    op.drop_index(
        "ix_institutions_name_trgm",
        table_name="institutions",
        postgresql_using="gin",
        postgresql_ops={"canonical_name": "gin_trgm_ops"},
    )
    op.drop_index(
        "ix_institutions_metro",
        table_name="institutions",
        postgresql_where=sa.text("metro_area IS NOT NULL"),
    )
    op.drop_index(
        "ix_institutions_legal_entity_norm",
        table_name="institutions",
        postgresql_where=sa.text("legal_entity_norm IS NOT NULL"),
    )
    op.drop_index(
        "ix_institutions_has_class_12",
        table_name="institutions",
        postgresql_where=sa.text("has_class_12 = true"),
    )
    op.drop_index(
        "ix_institutions_group",
        table_name="institutions",
        postgresql_where=sa.text("group_id IS NOT NULL"),
    )
    op.drop_index("ix_institutions_fee_min", table_name="institutions")
    op.drop_index("ix_institutions_fee_mid", table_name="institutions")
    op.drop_index("ix_institutions_enrollment", table_name="institutions")
    op.drop_index("ix_institutions_class_12", table_name="institutions")
    op.drop_table("institutions")
    op.drop_index("ix_fetches_url_requested", table_name="fetches")
    op.drop_index("ix_fetches_source_requested", table_name="fetches")
    op.drop_index("ix_fetches_content_hash", table_name="fetches")
    op.drop_table("fetches")
    op.drop_table("source_registry")
    op.drop_index(
        "ix_review_queue_kind_score",
        table_name="review_queue",
        postgresql_where=sa.text("state = 'open'"),
    )
    op.drop_table("review_queue")
    op.drop_table("raw_documents")
    op.drop_table("pipeline_runs")
    op.drop_index("ix_people_normalized_name", table_name="people")
    op.drop_table("people")
    op.drop_index(
        "uq_overrides_live",
        table_name="overrides",
        postgresql_where=sa.text("expires_at IS NULL"),
    )
    op.drop_table("overrides")
    op.drop_table("merge_decisions")
    op.drop_index(
        "ix_jobs_not_before_pending",
        table_name="jobs",
        postgresql_where=sa.text("state = 'pending'"),
    )
    op.drop_table("jobs")
    op.drop_table("groups")
    op.drop_table("eval_gold")
    op.drop_table("denylist_learned")
    # ### end Alembic commands ###
    op.execute("DROP EXTENSION IF EXISTS pg_trgm")
